version: "3"
services:
  AuctionServiceDB:
      image: postgres:14-alpine
      container_name: AuctionServiceDB
      ports:
        - 8081:5432
      volumes:
        - ./postgres-data:/1:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=1893
        - POSTGRES_USER=bognardev
        - POSTGRES_DB=auction-service


  ListingService:
    build:
      context: ./src/AuctionServices/ListingService
      dockerfile: Dockerfile
    container_name: listing-service
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./src/AuctionServices/ListingService:/app
    working_dir: /app
    command: [ "./main" ]
    depends_on:
      - AuctionServiceDB


  ViewingService:
    image: golang:1.21.3
    container_name: ViewService
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./src/AuctionServices/ViewService:/app
    working_dir: /app
    command: [ "./main" ]
    depends_on:
      - AuctionServiceDB

  BidderServiceDB:
        image: postgres:14-alpine
        container_name: BidderServiceDB
        ports:
            - 5433:8082
        volumes:
            - ./postgres-data:/2:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=1893
            - POSTGRES_USER=bognar-dev
            - POSTGRES_DB=bidder-service



